comp/urls.py
from django.urls import path
from . import views

app_name = 'comp'
urlpatterns = [
    path('list/', views.userComps,name='comp_list'),
    path('add/', views.compAdd,name='add'),
    path('<slug:slug>/', views.compSite,name='detail'),
    path('<slug:slug>/register/', views.compRegister, name='comp_register'),
    path('<slug:slug>/login/', views.compLogin, name='comp_login'),
    path('<slug:slug>/admin', views.compAdmin,name='admin'),
    path('<slug:slug>/admin/round/new', views.compCreateRound,name='round_create'),
    path('<slug:slug>/admin/round/<int:rnd>/edit', views.compEditRound,name='round_edit'),
	path('<slug:slug>/admin/round/<int:rnd>/delete', views.compDeleteRound,name='round_delete'),
    path('<slug:slug>/admin/round/<int:rnd>/form/sub/', views.roundFormSub, name='submission_form'),
    path('<slug:slug>/admin/round/<int:rnd>/form/evl/', views.roundFormEvl, name='evaluation_form'),
    path('<slug:slug>/profile/', views.participantProfile, name='participant_profile'),
    path('<slug:slug>/profile/<int:rnd>/', views.roundForm, name='round_form'),
]

minicompete/urls.py
from django.urls import path, include
from users import views

urlpatterns = [
    path('users/', include('users.urls')),
    path('comp/', include('comp.urls')),
    path('', views.loginview),
]

comp/models.py
import base_db
from pymongo.write_concern import WriteConcern
from pymodm import MongoModel, EmbeddedMongoModel, fields, ReferenceField
from users.models import User
db = base_db.db
# EMBEDDED MODELS
class Field(EmbeddedMongoModel):
	slug = fields.CharField(max_length=10)
	label = fields.CharField(max_length=150)
	css_classes = fields.ListField(field=fields.CharField())
	required = fields.BooleanField(default=False)
	type = fields.CharField(max_length=10) #select/text/paragraph
	tags = fields.ListField(field=fields.CharField())

class Form(EmbeddedMongoModel):
	type = fields.CharField(max_length=10)      #sub/evl
	title = fields.CharField(max_length=70)
	settings = fields.DictField()
	fields = fields.EmbeddedDocumentListField(Field)


#Model for the Rounds of a given competition
class Round(EmbeddedMongoModel):
    number = fields.IntegerField(min_value=1, max_value=10)
    title = fields.CharField(max_length=50)
    sub_start = fields.DateTimeField()
    sub_end = fields.DateTimeField()
    evl_start = fields.DateTimeField()
    evl_end = fields.DateTimeField()
    forms =  fields.EmbeddedDocumentListField(Form)


#Main Model for any  installation whether competition or anything that untap would support in the future.
class Install(MongoModel):
    slug = fields.CharField(primary_key=True)
    title = fields.CharField(max_length=100)
    owner = fields.ReferenceField(User, on_delete=ReferenceField.CASCADE)
    admins = fields.ListField(field=fields.ReferenceField(User)) #list of user objects
    rounds =  fields.EmbeddedDocumentListField(Round)

    class Meta:
        write_concern =  WriteConcern(j=True)
        connection_alias = 'comp'

    def __str__(self):
    	return self.slug
#######################################   End Install Classes  ##########################################




##The data to be submitted inside the form. (The ACTUAL FORM)
class EntryData(EmbeddedMongoModel):
    field_slug = fields.CharField()     ##For example the field that's called --> Title
    field_value = fields.CharField()   ##For example the value of the field that's called Title


##The whole submission information
class Entry(EmbeddedMongoModel):
    #The Entry should be unique per competition and round, not competition only nor round only. i.e test competition round 1 ->> Entry 1
    #There could be test competition round 2 --> Entry 1 again (The Entry is unique per competitin AND round)
    comp_ref = fields.ReferenceField(Install, on_delete=ReferenceField.CASCADE)
    round = fields.IntegerField()   #The round holding this Entry
    status = fields.CharField(max_length=100)   #The status of the submission
    sub_title = fields.CharField(max_length=200)  #the title of the submission
    sub_timestamp = fields.DateTimeField()          #the timestamp the applicant submitted the submission
    entry_data = fields.EmbeddedDocumentListField(EntryData) #the data inside the form of the submission
    average_score = fields.FloatField()     #Average score for the entry/submission from ALL the judges.
    tags = fields.ListField(field=fields.CharField(max_length=30))  #tags for the submission


class Applicant(EmbeddedMongoModel):
    applicant_ref = fields.ReferenceField(User, on_delete=ReferenceField.CASCADE)
    entries = fields.EmbeddedDocumentListField(Entry)



class Entries(MongoModel):
    applicant = fields.EmbeddedDocumentListField(Applicant) #List of user objects (participants/applicants)

    class Meta:
        write_concern =  WriteConcern(j=True)
        connection_alias = 'comp'
###############################################   End Entries Classes  #####################################################################

comp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from users.models import User
from .models import Install, Entry, Entries, Applicant, EntryData, db
from decorators import user_loggedin
from .forms import UserCompForm, RoundCreateForm, FormBuilder, CompRegisterForm, CompLoginForm
from datetime import datetime

@user_loggedin
def userComps(request):
	installs = Install.objects.all()
	return render(request, 'comp/list.html', {'installs': installs})

@user_loggedin
def compAdd(request):
	if request.method == 'POST':
		form = UserCompForm(request.POST)
		if form.is_valid():
			form.cleaned_data['owner'] = request.session['_auth_user_id']
			form.save()
			return redirect('comp:comp_list')
	else:
		form = UserCompForm()
	return render(request,'comp/add.html',{'form': form})


@user_loggedin
def compAdmin(request, slug):
	install = Install.objects.get({'_id': slug})
	return render(request, 'comp/admin.html', {'install': install})


@user_loggedin
def compCreateRound(request, slug):
	if request.method == 'POST':
		form = RoundCreateForm(request.POST)
		if form.is_valid():
			form.cleaned_data['slug'] = slug
			form.save()
			return redirect('comp:admin', slug=slug)
	else:
		form = RoundCreateForm()
	install = Install.objects.get({'_id': slug})
	return render(request, 'comp/new_round.html', {'install': install, 'form': form})



@user_loggedin
def compEditRound(request, slug, rnd):
	rund = None
	install = Install.objects.get({'_id': slug})
	for round in install.rounds:
		if round.number == rnd:
			rund = round
	if request.method == 'POST':
		form = RoundCreateForm(request.POST)
		if form.is_valid():
			form.cleaned_data['slug'] = slug
			form.cleaned_data['rnd'] = rnd
			form.update()
			return redirect('comp:admin', slug=slug)
	else:
		form = RoundCreateForm(initial={'title': rund.title, 'sub_start': rund.sub_start, 'sub_end': rund.sub_end, 'evl_start': rund.evl_start, 'evl_end': rund.evl_end})
	return render(request, 'comp/edit_round.html', {'install': install, 'form': form, 'rnd': rnd})


@user_loggedin
def compDeleteRound(request, slug, rnd):
	install = Install.objects.get({'_id': slug})
	del install.rounds[rnd - 1]
	install.save()
	return redirect('comp:admin', slug=slug)

@user_loggedin
def roundFormSub(request,slug, rnd):
	install = Install.objects.get({'_id': slug})
	round = install.rounds[rnd - 1]
	if request.method == 'POST':
		form = FormBuilder(request.POST)
		if form.is_valid():
			form.cleaned_data['form_type'] = "sub"
			form.cleaned_data['round_number'] = rnd
			form.save(install)
			return redirect('comp:submission_form', slug=slug, rnd=rnd)
	else:
		form = FormBuilder()
	return render(request,'comp/sub_form.html', {'install': install, 'round': round , 'form': form})


@user_loggedin
def roundFormEvl(request,slug, rnd):
	install = Install.objects.get({'_id': slug})
	round = install.rounds[rnd -1]
	if request.method == 'POST':
		form = FormBuilder(request.POST)
		if form.is_valid():
			form.cleaned_data['form_type'] = "evl"
			form.cleaned_data['round_number'] = rnd
			form.save(install)
			return redirect('comp:evaluation_form', slug=slug, rnd=rnd)
	else:
		form = FormBuilder()
	return render(request,'comp/evl_form.html', {'install': install, 'round': round , 'form': form})



def compSite(request, slug):
	install = Install.objects.get({'_id': slug})
	register_form = CompRegisterForm()
	login_form = CompLoginForm()
	return render(request, 'comp/detail.html', {'install': install, 'register_form': register_form, 'login_form': login_form})



def compRegister(request,slug):
	"""
	A function that registers a user to the competition
	"""
	if request.method == 'POST':
		form = CompRegisterForm(request.POST)
		if form.is_valid():
			user = form.save(slug)
			if user == 1:
				messages.add_message(request,messages.INFO, 'Passwords do not match')

			elif user == 2:
				messages.add_message(request,messages.INFO, 'The user already exists in this competition. Please Login')
			else:
				messages.add_message(request,messages.INFO, 'User is added successfully to the competition')

			return redirect('comp:detail', slug=slug)



def compLogin(request,slug):
	if request.method == 'POST':
		form = CompLoginForm(request.POST)
		if form.is_valid():
			user = form.save(request,slug)
			if user == 1:
				messages.add_message(request,messages.WARNING, 'User Does not exist in this competition')
			elif user == 2:
				messages.add_message(request,messages.WARNING, 'Invalid Password Entered. Please try again.')
			elif user == 3:
				messages.add_message(request,messages.WARNING, 'Invalid Username entered. Please try again')
			else:
				messages.add_message(request, messages.WARNING, 'User is logged in successfully!')
				return redirect('comp:participant_profile', slug=slug)

			return redirect('comp:detail', slug=slug)


def participantProfile(request,slug):
	install = Install.objects.get({'_id': slug})
	return render(request,'comp/participant_profile.html', {'install': install})

def roundForm(request,slug,rnd):
	install = Install.objects.get({'_id':slug})
	round_forms = install.rounds[rnd - 1].forms
	if request.method == 'POST':
		user = User.get_current_user(request)
		entry_key = None
		entry_data = []
		for key, data in request.POST.items():
			if key == 'csrfmiddlewaretoken':
				continue
			entry_data.append(EntryData(field_slug=key, field_value=data))

		if Entries.objects.count() > 0:
			ents = list(Entries.objects.all())
			app_key = None
			user_exists, entry_exists, same_round = (False,False,False)
			for et_key, entry in enumerate(ents):
				applicant_list = list(entry.applicant)
				for key, app in enumerate(applicant_list):
					if app.applicant_ref == user:
						user_exists = True
						app_key = key
						entry_key = et_key
						applicant_entries = list(app.entries)
						for ent_key, ent in enumerate(applicant_entries):
							if ent.comp_ref.slug == slug:
								entry_exists = True
								if ent.round == rnd:
									same_round = True
									break
						break
		else:
			app_entry = [Entry(comp_ref=slug, round=rnd, status='applied', sub_timestamp=datetime.now(), entry_data=entry_data)]
			applicant = [Applicant(applicant_ref=user, entries=app_entry)]
			entry = Entries(applicant=applicant)
			entry.save()
			return redirect('comp:participant_profile', slug=slug)

		####Checkings for adding a new entry to the database.
		if not user_exists:
			##User is not found in the entries collection, so add a completely new applicant to the list.
			app_entry = [Entry(comp_ref=slug, round=rnd,status='applied', sub_timestamp=datetime.now(),entry_data=entry_data)]
			applicant = [Applicant(applicant_ref=user, entries=app_entry)]
			entry = Entries(applicant= applicant)
			entry.save()
			return redirect('comp:participant_profile', slug=slug)
		elif (user_exists and not entry_exists) or (user_exists and entry_exists and not same_round):
			app_entry = Entry(comp_ref=slug, round=rnd, status='applied', sub_timestamp=datetime.now(), entry_data=entry_data)
			entrs = Entries.objects.all()
			enry = entrs[entry_key]
			enry.applicant[app_key].entries.append(app_entry)
			enry.save()
			return redirect('comp:participant_profile', slug=slug)

		elif user_exists and entry_exists and same_round:
			messages.add_message(request, messages.INFO, 'You already submitted this application before.')
			##ERROR, EXISTING ENTRY ALREADY THERE.

	final_form = None
	for form in round_forms:
		if form.type == "sub":
			final_form = form

	return render(request,'comp/round_form.html', {'form': final_form, 'round': rnd, 'slug': slug})

comp/templates/comp/add.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Create Competition</h1>
<div class="form">
<form class="site-form" method="post" action="{% url 'comp:add' %}">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Add" />
</form>
</div>

{% endblock %}

comp/templates/comp/admin.html
{% extends 'base_admin.html' %}

{% block content %}

<h1>{{install.title}} Rounds</h1>

<table class="table">
	<tr>
		<th>Number</th>
		<th>Title</th>
		<th>Action</th>
	</tr>
	{% for round in install.rounds %}
	<tr>
		<th>{{round.number}}</th>
		<th>{{round.title}}</th>
		<th>
			<a href="{% url 'comp:round_edit' install.pk round.number %}" >Edit</a> &emsp;
			<a href="{% url 'comp:round_delete' install.pk round.number %}">Delete</a> &emsp;
			<a href="{% url 'comp:submission_form' install.pk round.number %}">Submission</a> &emsp;
            <a href="{% url 'comp:evaluation_form' install.pk round.number %}">Evaluation</a> &emsp;
		</th>
	</tr>
	{% endfor %}
</table>


{% endblock %}

comp/templates/comp/detail.html
{% extends 'base_comp.html' %}

{% block content %}
    <br/>
    <br/>

<h1 style="color:#000000" class="text-center">{{install.title}}</h1>
<div class="container">
<div class="col-md-6">
    <div id="logbox">
        <form class= "comp_forms" id="comp_signup" method="post" action="{% url 'comp:comp_register' install.slug %}">
        {% csrf_token %}

        <h1>Sign up to {{ install.title }}</h1>
            {% if messages.level == 20 %}
    <ul class="messages">
{% for message in messages %}
    <li >{{ message }}</li>
    {% endfor %}
</ul>
 {% endif %}
            {{ register_form }}
        <input type="submit" value="Sign up" class="inputButton"/>
        </form>
    </div>
</div>

   <div class="col-md-6">
    <div id="logbox">
      <form class= "comp_forms" id="comp_signin" method="post" action="{% url 'comp:comp_login' install.slug %}">
          {% csrf_token %}
          <h1>Log in to {{ install.title}}</h1>
            {% if messages.level == 30 %}
    <ul class="messages">
{% for message in messages %}
    <li >{{ message }}</li>
    {% endfor %}
</ul>
 {% endif %}
          {{ login_form }}
          <input type="submit" value="Sign in" class="inputButton"/>
      </form>
    </div>
    </div>
  </div>
{% endblock %}

comp/templates/comp/edit_round.html
{% extends 'base_admin.html' %}

{% block content %}

<h1>Edit Round for {{install.title}}</h1>
<div class="form">
<form class="site-form" method="post" action="{% url 'comp:round_edit' install.pk rnd %}">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Add" />
</form>
</div>

{% endblock %}

comp/templates/comp/evl_form.html
{% extends 'base_admin.html' %}

{% block content %}

<h1>{{round.title}} Evaluation Form</h1>

<form method="post" action="{% url 'comp:evaluation_form' install.pk round.number %}">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary" >Add</button>
</form>
    <br/>
    <br/>
{% for form in round.forms %}
    {% if form.type == 'evl' %}
        {% for field in form.fields %}
    <div style="border: 1px solid #fff; margin-bottom: 10px;padding: 15px;">
        {{ field.label }}
    </div>
        {% endfor %}
    {% endif %}
{% endfor %}


{% endblock %}

comp/templates/comp/list.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>My competitions</h1>
<p><a href="{% url 'comp:add' %}" class="btn btn-primary">Create New</a></p>

<table class="table">
	<tr>
		<th>Title</th>
		<th>slug</th>
		<th># of rounds</th>
		<th>Action</th>
	</tr>
	{% for comp in installs %}
	<tr>
		<th>{{comp.title}}</th>
		<th>{{comp.pk}}</th>
		<th>{{comp.rounds.count}}</th>
		<th>
			<a href="{% url 'comp:detail' comp.pk %}" >View</a> &emsp;
			<a href="{% url 'comp:admin'  comp.pk %}">Manage</a>
		</th>
	</tr>
	{% endfor %}
</table>




<script>
	function show_mdl(obj, e){
		e.preventDefault();
		jQuery('.modal').modal('show');
	}
</script>

{% endblock %}

comp/templates/comp/new_round.html
{% extends 'base_admin.html' %}

{% block content %}

<h1>Create Round for {{install.title}}</h1>
<div class="form">
<form class="site-form" method="post" action="{% url 'comp:round_create' install.pk %}">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Add" />
</form>
</div>

{% endblock %}

comp/templates/comp/participant_profile.html
{% extends 'base_comp.html' %}

{% block content %}
    <br/>
    <br/>
<h1 style="margin-left: 30px">{{ install.title  }} Rounds</h1>
    <ul>
    {% if install.rounds %}
        {% for round in install.rounds %}
        <li style="list-style-type: none"><a href="{% url 'comp:round_form' install.pk round.number %}">{{ round.title }}</a></li>
        {% endfor %}

    {% endif %}
    </ul>
{% endblock %}

comp/templates/comp/round_form.html
{% extends 'base_comp.html' %}

{% block content %}
    <br/>
    <br/>
<h1 style="margin-left: 30px">{{ form.title }}</h1>
    <form style="max-width: 80%; margin: 0 auto" action="{% url 'comp:round_form' slug round %}" method="post">
    {% csrf_token %}
      {% if messages %}
    <ul class="messages">
{% for message in messages %}
    <li >{{ message }}</li>
    {% endfor %}
    {% endif %}
</ul>
        {% if form.fields %}
    {% for field in form.fields %}

        {% if field.type == 'text' %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                <input type="text" name="{{ field.slug }}" class="form-control" {% if field.required %} required="required" {% endif %}/>
            </div>
        {% elif field.type == 'textarea' %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                <textarea name="{{ field.slug }}" class="form-control" {% if field.required %} required="required" {% endif %}></textarea>
            </div>
        {% endif %}

    {% endfor %}
    <input type="submit" value="Submit" />
    {% else %}
        <p class="text-center">Application form is not ready yet.</p>
    {% endif %}
    </form>
{% endblock %}

comp/templates/comp/sub_form.html
{% extends 'base_admin.html' %}

{% block content %}

<h1>{{round.title}} Submission Form</h1>

<form method="post" action="{% url 'comp:submission_form' install.pk round.number %}">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary" >Add</button>
</form>
    <br/>
    <br/>
{% for form in round.forms %}
    {% if form.type == 'sub' %}
        {% for field in form.fields %}
    <div style="border: 1px solid #fff; margin-bottom: 10px;padding: 15px;">
        {{ field.label }}
    </div>
        {% endfor %}
    {% endif %}
{% endfor %}
{% endblock %}