comp/urls.py
from django.urls import path
from . import views

app_name = 'comp'
urlpatterns = [
    path('list/', views.userComps,name='comp_list'),
    path('add/', views.compAdd,name='add'),
    path('<slug:slug>/', views.compSite,name='detail'),
    path('<slug:slug>/register/', views.compRegister, name='comp_register'),
    path('<slug:slug>/login/', views.compLogin, name='comp_login'),
    path('<slug:slug>/admin', views.compAdmin,name='admin'),
    path('<slug:slug>/admin/round/new', views.compCreateRound,name='round_create'),
    path('<slug:slug>/admin/round/<int:rnd>/edit', views.compEditRound,name='round_edit'),
	path('<slug:slug>/admin/round/<int:rnd>/delete', views.compDeleteRound,name='round_delete'),
    path('<slug:slug>/admin/round/<int:rnd>/form/sub/', views.roundFormSub, name='submission_form'),
    path('<slug:slug>/admin/round/<int:rnd>/form/evl/', views.roundFormEvl, name='evaluation_form'),
    path('<slug:slug>/profile/', views.participantProfile, name='participant_profile'),
    path('<slug:slug>/profile/<int:rnd>/', views.roundForm, name='round_form'),
]

minicompete/urls.py
from django.urls import path, include
from users import views

urlpatterns = [
    path('users/', include('users.urls')),
    path('comp/', include('comp.urls')),
    path('', views.loginview),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.loginview,name='login_user'),
    path('register/', views.registerview,name='register_user'),
    path('logout/', views.logoutview,name='logout_user'),
    path('profile/', views.profileview,name='profile'),
    path('all/', views.usersview,name='all'),
    path('<slug:username>/delete/', views.deleteuser,name='delete'),
    path('<slug:username>/edit/', views.edituser,name='edit'),
]

users/models.py
import base_db
from pymongo.write_concern import WriteConcern
from pymodm import MongoModel, EmbeddedMongoModel, fields, ReferenceField

# EMBEDDED MODELS
class Name(EmbeddedMongoModel):
    first = fields.CharField(max_length=50)
    last = fields.CharField(max_length=50)


class Role(EmbeddedMongoModel):
    comp_ref = fields.CharField(max_length=20)
    role = fields.CharField(max_length=20)


#Main Model
class User(MongoModel):
    email = fields.EmailField(primary_key=True)
    username = fields.CharField(max_length=50)
    password = fields.CharField(max_length=50)
    name = fields.EmbeddedDocumentField(Name)
    roles =  fields.EmbeddedDocumentListField(Role)
    last_access = fields.DateTimeField()
    created_at = fields.DateTimeField()
    extra = fields.DictField()

    class Meta:
        write_concern =  WriteConcern(j=True)
        connection_alias = 'comp'

    def __str__(self):
    	return self.email

    def get_current_user(request):
    	pk = request.session['_auth_user_id']
    	return User.objects.get({'_id': pk}) if '_auth_user_id' in request.session else None

    def is_user_loggedin(request):
    	if '_auth_user_id' in request.session:
    		pk = request.session['_auth_user_id']  
    		return True if User.objects.get({'_id': pk}) is not None else False
    	else: 
    		return False


    def is_admin(request):
        if User.is_user_loggedin(request):
            pk = request.session['_auth_user_id']
            user = User.objects.get({'_id': pk})
            for role in user.roles:
                if role.comp_ref == 'main' and role.role == 'admin':
                    if '_authorized' not in request.session:
                        request.session['_authorized'] = 1
                    return True
        return False

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from users.models import User as UserMongo
from users.models import Name
import logging


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(label="Email", required=True)


    def save(self,commit=True):
        if commit:
            user = UserMongo()
            #Get the form information
            new_user_email = self.cleaned_data["email"]
            new_user_password = self.cleaned_data["password1"]
            new_user_username = self.cleaned_data["username"]

            try:
                UserMongo.objects.get({'_id': new_user_email})
                return 'User Already exists with this email'
            except UserMongo.DoesNotExist:
                #Place the new information into the user object and save it into mongo.
                user.email = new_user_email
                user.password = new_user_password
                user.username = new_user_username
                user.save()
                return 'User is created successfully!'

class UserLoginForm(forms.Form):
    email = forms.EmailField(label="Email", required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    def login(self,request,commit=True):
        """
          A function that performs the save function of the login view.
          THE POST function of the Login form.
        """
        if commit:
           ##Get the Login Data, Email and Password
            submitted_email = self.cleaned_data["email"]
            submitted_password = self.cleaned_data["password"]

            try:
                user = UserMongo.objects.get({'_id': submitted_email})
                if user.password == submitted_password:
                    request.session['_auth_user_id'] = user.email
                    # request.session['next'] = 'posts:posts_list'
                    request.user = user
                    return user
                else:
                    return 1  # Invalid Password entered

            except UserMongo.DoesNotExist:
                return 2  # Invalid Username entered
        


    
class UserProfileForm(forms.Form):
    first = forms.CharField(label="First Name")
    last = forms.CharField(label="Last Name")
    interests = forms.CharField(label="Interests")
    job = forms.CharField(label="Job")
    edu_level = forms.CharField(label="Education Level")

    def save(self,commit=True):
        #Get the form information
        extras = {
        'interests': self.cleaned_data["interests"],
        'job': self.cleaned_data["job"],
        'edu_level': self.cleaned_data["edu_level"]
        }

        user = UserMongo.objects.get({'_id': self.cleaned_data["email"]})
        user.extra = extras
        user.name = {'first': self.cleaned_data["first"], 'last': self.cleaned_data["last"]}
        user.save()
        return user

users/views.py
from django.shortcuts import render,redirect
from users.forms import UserCreationForm, UserLoginForm, UserProfileForm
from .models import User, Role
from decorators import user_loggedin
import datetime
from django.http import JsonResponse

# Create your views here.
def loginview(request):
    message = None
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = form.login(request=request)
            if user == 1:
                message = 'Invalid Password Entered. Please try again'
            elif user == 2:
                message = 'There is no username with this email.'
            else:
                User.is_admin(request)
                user.last_access = datetime.datetime.now()
                user.save()
                #User is authenticated successfully, redirect to the profile page.
                return redirect('users:profile')

    else:
        form = UserLoginForm()

    if '_auth_user_id' not in request.session:
        return render(request,'users/login.html',{'form': form, 'error_msg': message})
    else:
        return redirect('users:profile')



def registerview(request):
    message = None
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            message = form.save()
            return redirect('users:profile')
    else:
        form = UserCreationForm()
    return render(request,'users/sign_up.html',{'form': form, 'error_msg': message})



def logoutview(request):
	request.session.flush()
	return redirect('users:login_user')


@user_loggedin
def profileview(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.cleaned_data['email'] = request.session['_auth_user_id']
            user = form.save()
            return redirect('users:profile')
    else:
        user = User.get_current_user(request)
        if user.extra:
            form = UserProfileForm(initial={'interests': user.extra['interests'],'job': user.extra['job'],'edu_level': user.extra['edu_level'], 'first': user.name.first, 'last': user.name.last})
        else:
            form = UserProfileForm()
    return render(request,'users/profile.html',{'form': form, 'user': user})


@user_loggedin
def usersview(request):
    if User.is_admin(request):
        users = User.objects.all()
        return render(request, 'users/all.html', {'users': users})
    else:
        return redirect('users:profile')



@user_loggedin
def deleteuser(request, username):
    if User.is_admin(request):
        user = User.objects.get({'username': username})
        user.delete()
    return redirect('users:all')


@user_loggedin
def edituser(request, username):
    if User.is_admin(request) and request.method == 'POST':
        user = User.objects.get({'username': username})
        user.roles = [ Role(comp_ref = 'main', role = request.POST['role']) ]
        user.save()
    return redirect('users:all')

users/templates/users/all.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>User Management</h1>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Last Access</th>
		<th>Action</th>
	</tr>
	{% for user in users %}
	<tr>
		<th>{{user.username}}</th>
		<th>{{user.pk}}</th>
		<th>{{user.last_access}}</th>
		<th>
			<a href="#/edit" onclick="show_mdl(this, event)" data-toggle="modal" data-user="{{user.pk}}" data-target="#{{user.username}}Mdl">Edit</a> &emsp;
			<a href="{% url 'users:delete' user.username %}">Delete</a>


			<!-- Modal -->
			<div class="modal" id="{{user.username}}Mdl" tabindex="-1" role="dialog" aria-labelledby="usrMdlLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="exampleModalLabel">Edit User</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <form action="{% url 'users:edit' user.username %}" method="post">
			      	{% csrf_token %}
				      <div class="modal-body">
				        <label for="userrole">User Role</label>
				        <select id="userrole" name="role">
				        	<option value="">- Select Role -</option>
				        	<option value="participant">Participant</option>
				        	<option value="judge">Judge</option>
				        	<option value="admin">Admin</option>
				        </select>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				        <button type="submit" class="btn btn-primary">Save changes</button>
				      </div>
			  	  </form>
			    </div>
			  </div>
			</div>
		</th>
	</tr>
	{% endfor %}
</table>




{#<script>#}
{#	function show_mdl(obj, e){#}
{#		e.preventDefault();#}
{#		jQuery('.modal').modal('show');#}
{#	}#}
{#</script>#}

{% endblock %}

users/templates/users/login.html
{% extends 'base_layout.html' %}

{% block content %}


<h1>Login</h1>
    <div class="form">
      <form class="site-form" action="{% url 'users:login_user' %}" method="post">
        {% csrf_token %}
          {% if error_msg %}
   <div class="alert alert-danger">
   <strong>{{ error_msg }}</strong>
   </div>
{% endif %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
    </div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base_layout.html' %}

{% block content %}
<style type="text/css">
	.site-form p:first-of-type{
		width: 50%;
    	float: left;
	}
	h5{ color: #fff; }
</style>
<h1>User Profile</h1>
<div class="form">
    <form class="site-form" action="{% url 'users:profile' %}" method="post">
        {% csrf_token %}
        <h5>Name</h5>
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</div>

{% endblock %}

users/templates/users/sign_up.html
{% extends 'base_layout.html' %}
{% block content %}
{% if error_msg %}
   <div class="alert alert-danger">
   <strong>{{ error_msg }}</strong>
   </div>
{% endif %}


<h1>Signup</h1>
    <div class="form">
    <form class="site-form" action="{% url 'users:register_user' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
    </div>
{% endblock %}