comp/urls.py
from django.urls import path
from . import views

app_name = 'comp'
urlpatterns = [
    path('list/', views.userComps,name='comp_list'),
    path('add/', views.compAdd,name='add'),
    path('<slug:slug>/', views.compSite,name='detail'),
    path('<slug:slug>/register/', views.compRegister, name='comp_register'),
    path('<slug:slug>/login/', views.compLogin, name='comp_login'),
    path('<slug:slug>/admin', views.compAdmin,name='admin'),
    path('<slug:slug>/admin/round/new', views.compCreateRound,name='round_create'),
    path('<slug:slug>/admin/round/<int:rnd>/edit', views.compEditRound,name='round_edit'),
	path('<slug:slug>/admin/round/<int:rnd>/delete', views.compDeleteRound,name='round_delete'),
    path('<slug:slug>/admin/round/<int:rnd>/form/sub/', views.roundFormSub, name='submission_form'),
    path('<slug:slug>/admin/round/<int:rnd>/form/evl/', views.roundFormEvl, name='evaluation_form'),
    path('<slug:slug>/profile/', views.participantProfile, name='participant_profile'),
    path('<slug:slug>/profile/<int:rnd>/', views.roundForm, name='round_form'),
]

minicompete/urls.py
from django.urls import path, include
from users import views

urlpatterns = [
    path('users/', include('users.urls')),
    path('comp/', include('comp.urls')),
    path('', views.loginview),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.loginview,name='login_user'),
    path('register/', views.registerview,name='register_user'),
    path('logout/', views.logoutview,name='logout_user'),
    path('profile/', views.profileview,name='profile'),
    path('all/', views.usersview,name='all'),
    path('<slug:username>/delete/', views.deleteuser,name='delete'),
    path('<slug:username>/edit/', views.edituser,name='edit'),
]

templates/base_admin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>


    
    <meta charset="UTF-8">
    <title>Mini Compete</title>
</head>
<body>
<div class="wrappertest">
    <h1><a href="#"><img src="{% static 'logo.png' %}"/></a></h1>

    <div class="row">
        <div class="col-md-8">
        {% block content %}
        {% endblock %}
        </div>
        <div class="col-md-4">
            <ul class="list-group">
              <li class="list-group-item"><a href="{% url 'comp:round_create' install.pk %}">New Round</a></li>
              {% if install %}
              <li class="list-group-item"><a href="{% url 'comp:admin' install.pk %}">All Rounds</a></li>
              {% endif %}

              {% if '_auth_user_id' in request.session %}
                <li class="list-group-item">
                    <form class="logout-link"  action="{% url 'users:logout_user' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
               {% endif %}
            </ul>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
</div>
</body>
</html>

templates/base_comp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <meta charset="UTF-8">
    <title>Mini Compete</title>
</head>
<body id="comp_main">
{% block content %}
{% endblock %}
 <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>


    <meta charset="UTF-8">
    <title>Mini Compete</title>
</head>
<body>
<div class="wrappertest">
    <h1><a href="#"><img src="{% static 'logo.png' %}"/></a></h1>
    <nav>
        <ul id="actionul">
            {% if '_auth_user_id' in request.session %}
                <li class="actionbutton">
                    <form class="logout-link"  action="{% url 'users:logout_user' %}" method="post">
                        {% csrf_token %}
                        <button id="logout_base" type="submit">Logout</button>
                    </form>
                </li>
                <li class="actionbutton"><a href="{% url 'users:profile' %}" class="highlight">Profile</a></li>
                {% if '_authorized' in request.session %}
                    <li class="actionbutton"><a href="{% url 'users:all' %}" class="highlight">Manage Users</a></li>
                    <li class="actionbutton"><a href="{% url 'comp:comp_list' %}" class="highlight">Manage Competitions</a></li>
                {% endif %}

            {% else %}
                <li class="actionbutton"><a href="{% url 'users:login_user' %}">Login</a></li>
                <li class="actionbutton"><a href="{% url 'users:register_user' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
</div>
</body>
</html>